[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid
loglevel=info

[unix_http_server]
file=/var/run/supervisor.sock

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

; -----------------------------
; PHP-FPM (основной web процесс)
; -----------------------------
[program:php-fpm]
command=php-fpm -F
directory=/var/www
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
stopasgroup=true
killasgroup=true

; -----------------------------
; Symfony Messenger Worker
; -----------------------------

[program:messenger_worker]
command=php /var/www/bin/console messenger:consume scheduler_quick_tickets scheduler_telegram_poll -vv --no-debug --time-limit=3600 --memory-limit=128M --no-interaction
directory=/var/www
autostart=true
autorestart=true
user=www-data

stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

stopasgroup=true
killasgroup=true